#Project 2: Stack & Queue ADT Juggler
#Programmer: Ian Royer
#Course: Dr. Lee
#Professor: Dr. Lee

SOURCES = sqjuggler.c stackADT.c queueADT.c
OBJECTS = sqjuggler.c stackADT.c queueADT.c
HEADERS = sqjuggler.h stackADT.h queueADT.h
CFLAGS = -g -Wall

sqjuggler: $(OBJECTS)
	     $(CC) $(CFLAGS) $(OBJECTS) -o sqjuggler

clean:
	rm -fR *o sqjuggler
